#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.

server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db_card
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

security:
  jwt:
    secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
    iteration: 64
    keyLength: mysecret
  secret:  b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 36000
  issuer: misha

swagger:
  enabled: true

card:
  encryption:
    key: ${KEY}
    iv: ${IV}