server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml

security:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

logging:
  level:
    root: DEBUG

swagger:
  enabled: true

card:
  encryption:
    key: ${KEY}
    vector: ${VECTOR}

preload:
  admin: true

data:
  expired:
    value: 10
  admin:
    password: ${ADMIN_PASSWORD}